make qsort:
	gcc -o bin/quicksort quicksort.c
	.\bin\quicksort.exe

make msort:
	gcc -o bin/mergesort mergesort.c
	.\bin\mergesort.exe

make bs:
	gcc -o bin/binary_search binary_search.c
	.\bin\binary_search.exe

make rand:
	gcc -o bin/random random.c
	.\bin\random.exe

make cad:
	gcc -o bin/cadenas cadenas.c
	.\bin\cadenas.exe